services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: it-caribe-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ../it-caribe-backend:/var/www
    networks:
      - it-caribe-network

networks:
  it-caribe-network:
    external: true