services:
  nginx:
    image: docker.io/bitnami/nginx:1.28
    ports:
      - '80:8080'
    container_name: it-caribe-nginx
    restart: unless-stopped
    volumes:
      - ./conf/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf:ro
    networks:
      - it-caribe-network

networks:
  it-caribe-network:
    external: true